### ISSUE TITLE
VS 2017 Docker issue with CASB Certificate

### ISSUE THREAD

**Issue by dstrebel** [microsoft/DockerTools#187] opened 2019-05-14 17:08 UTC
Brief Issue Summary
Issue only occurs when running from VS 2017 integrated tooling – running from command line does not trigger issue

Running NetSkope locally as a CASB
We Needed to add NetSkope Intermediate and Root CA as trusted certs in our container for local execution.

When executed from VS, the CASB certificates apparently are untrusted, leading to SSL errors on certain domains (i.e., most Azure management domains, such as those issuing access tokens)

We’ve attempted to diagnose what/how VS injects itself (vsdbg) into the Docker runtime for debugging, but I’ve yet to find a means to customize this behavior or to add an additional trusted certificate. We’re 100% certain the root cause is the CASB proxying traffic, as we can temporarily disable it and execute without issue.

**Comment by sgreenmsft** [comment] 2019-05-14 18:37
How are you adding these certs in your container?  I'm guessing this is done in your dockerfile -- are you able to share the dockerfile contents?

As a general explanation of how Visual Studio handles debugging: In order to make debugging as fast as possible, Visual Studio cheats.  Rebuilding the entire Dockerfile every time you F5 is very slow, so instead Visual Studio just builds the first stage (the "base" stage) of the Dockerfile and assumes that this will produce a more or less empty image.  That empty image is then run with your project's output directory volume mounted into the container at /app.  In this way you're debugging the code that was compiled on your machine instead of in a container.  When you stop debugging, make a code change, and then F5 again, Visual Studio re-uses the already running container.  So if your Dockerfile includes a configuration change that is needed for F5, you'll want to make that change in the base stage.

As a general explanation of how Visual Studio handles vsdbg:  vsdbg is volume mounted into the container at /remote_debugger.  The container's entrypoint is overridden to just be a call to tail, which is done to keep the container alive across multiple F5 operations.  Visual Studio launches vsdbg inside of the container using docker exec.

**Comment by droessmj** [comment] 2019-05-14 20:55
@dstrebel - thanks for opening this. 

Complete Dockerfile, with redactions due to enterprise concerns:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.3 AS base
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:5000 \
    DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 5000

FROM mcr.microsoft.com/dotnet/core/sdk:2.2.105 AS build
WORKDIR /src
COPY ["Project/Project.csproj", "Project/"]
RUN dotnet restore "Project/Project.csproj"
COPY . .
WORKDIR "/src/Project"
RUN dotnet build "Project.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Project.csproj" -c Release -o /app

FROM base AS final
COPY ["SampleWebBasic/CERT.crt", "/usr/local/share/ca-certificates/CERT.crt"]
RUN update-ca-certificates
# USER dotnetappuser (for future use)
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Project.dll"]
```

If I'm following your response above, we need to take action against the base image? Could you briefly share how this action would be taken in the below flow, where the base image is a third party dotnet container?

**Comment by sgreenmsft** [comment] 2019-05-14 22:35
@droessmj - Thanks for sharing the Dockerfile!

In short, you would move the lines that are installing the certs up from the final stage of the dockerfile into the base stage of the dockerfile, like so:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.3 AS base
WORKDIR /app
COPY ["SampleWebBasic/CERT.crt", "/usr/local/share/ca-certificates/CERT.crt"]
RUN update-ca-certificates
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/core/sdk:2.2.105 AS build
WORKDIR /src
COPY ["Project/Project.csproj", "Project/"]
RUN dotnet restore "Project/Project.csproj"
COPY . .
WORKDIR "/src/Project"
RUN dotnet build "Project.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Project.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Project.dll"]
```

To clarify, when you F5 in Visual Studio, it will call docker build using the argument "--target=base".  This tells Docker to ignore everything in the Dockerfile after the line EXPOSE 5000.

Side-note: I removed the DOTNET_RUNNING_IN_CONTAINER=true environment variable because that's already specified in the mcr.microsoft.com/dotnet/core/aspnet:2.2.3 image that you're building on.

**Comment by droessmj** [comment] 2019-05-15 00:35
@sgreenmsft - Thank you! I believe I tried more or less what you have above without luck, although I had the COPY and RUN update-ca-certificates before the WORKDIR /app. I'll give it another go in the morning. 

I can confirm I had success doing a local build consisting of:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.3 
COPY ["SampleWebBasic/CERT.crt", "/usr/local/share/ca-certificates/CERT.crt"]
RUN update-ca-certificates
WORKDIR /app
```
and then using this image as my base within my VS build. For our use cases, I believe we could bake the cert into a base image for developer consumption if needed. 

Any chance of future configuration settings (or just additional detailed documentation) highlighting this behavior? We've lived with this for a while now as the discoverability of this behavior was more or less non-existent. This workaround will make a few people's week. 

Also, thanks for the note on DOTNET_RUNNING_IN_CONTAINER.

**Comment by sgreenmsft** [comment] 2019-05-15 00:54
Sounds great.

We hear you about the lack of documentation/discoverability.  As a first step we're working to improve the VS container tools documentation -- especially the magic that Visual Studio does to make Docker debugging fast and the msbuild properties that can be used to control some of that behavior.  Now that the Build conference has wrapped we should have some time to get this documentation done.

**Comment by droessmj** [comment] 2019-05-15 12:22
Thanks @sgreenmsft and @dstrebel. I think this issue is resolved with a viable workaround given the new info shared. Appreciate the quick help!

**Comment by bwateratmsft** [comment] 2019-05-15 15:40
Glad it's working @droessmj!

**Closed by bwateratmsft** 2019-05-15 15:40 UTC
