### ISSUE TITLE
Cannot start Docker debug with VS2017 15.3

### ISSUE THREAD

**Issue by joye-ramone** [microsoft/DockerTools#37] opened 2017-08-16 09:48 UTC
After upgrade to latest VS 2017 15.3 I cannot start debug of Docker container from VS.
Reproducible with any kind of .net core projects (console, asp.net) and with any version of .net core.

I also tried to start VS with admin rights, restart my box and stop and start docker.

Error message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
Docker log:
```
docker-compose -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\docker-compose.yml" -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\docker-compose.override.yml" -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose9756074155277170669 config
services:
  consoleapp1:
    build:
      args:
        source: obj/Docker/empty/
      context: C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    environment:
      NUGET_FALLBACK_PACKAGES: /root/.nuget/fallbackpackages
    image: consoleapp1:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages
        --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.0/ConsoleApp1.dll'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/bash -c "if PID=$(pidof
        -x dotnet); then kill $PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    volumes:
    - C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1:/app:rw
    - C:\Users\Sergii_Tkachenko\vsdbg:/remote_debugger:ro
    - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
    - C:\Users\Sergii_Tkachenko\.nuget\packages:/root/.nuget/packages:ro
version: '3.0'
docker  ps --filter "status=running" --filter "name=dockercompose9756074155277170669_consoleapp1_" --format {{.ID}} -n 1
1f2a3ec3b102
```

But, I can see that image created and container is up and running using docker -ps:
docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
1f2a3ec3b102        consoleapp1:dev     "tail -f /dev/null"   16 hours ago        Up About a minute                       dockercompose9756074155277170669_consoleapp1_1

**Comment by HK-Zhang** [comment] 2017-08-28 01:12
I got the same issue on VS 2017.15.3.2 Professional.

**Comment by dbreshears** [comment] 2017-08-28 19:01
This is probably caused by the base images being stale.  I recently repro'd this  and fixed by  pulling the base image again,   (i.e. docker pull microsoft/aspnetcore:2.0) or the version you are working with.   You should also do a clean solution or delete your docker image so that it gets rebuilt.    Can you try this and let me know.

**Comment by dbreshears** [comment] 2017-08-28 23:48
One additional item that could have played a role in fixing for me was to reset the Shared Drives authentication in Docker for Windows.  Rick click the tray icon and select Settings..., open Shared Drives tab and share the drives again by resetting credentials.   It looked like volume mapping was not working from the container to the host.

**Comment by jo-ninja** [comment] 2017-09-01 03:03
Pulling the base image again and resetting credentials did not work for me (VS Community 2017 version 15.3.3).

Solved it by referring to https://github.com/dotnet/dotnet-docker/issues/162#issuecomment-262940984, **but** instead of `%userprofile%\clrdbg`, I needed to delete `%userprofile%\vsdbg`.

**Comment by joye-ramone** [comment] 2017-09-01 19:11
Same for me. Was able to fix an issue with remove of %userprofile%\clrdbg

**Comment by ConradMostert** [comment] 2018-01-09 14:07
Thanks, had to all three (reset credentials, remove images and deleted %userprofile%\vsdbg) before success

**Comment by pernix84** [comment] 2018-02-13 11:01
In what order have you executed the steps, which helped to solve the problem? It seems I have the same problem, executed all steps, rebuilt the solution, but it doesn't seem to be working. However, the image is running correctly, but the VsDbg cannot be started.

**Comment by nicksterx** [comment] 2018-02-13 17:49
Same issue. I have reset credentials, removed and recreated images, and deleted vsdbg. 

Microsoft Visual Studio Enterprise 2017 Version 15.5.6

Docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by pernix84** [comment] 2018-02-14 11:40
Sorry, I missed to add my docker versions as well.
Visual Studio Professional 15.5.6

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by nicksterx** [comment] 2018-02-14 15:54
@pernix84 My application starts. And other dlls have their symbols loaded properly. It's the main application started by the docker container that doesn't have its symbols loaded.

**Comment by IharYakimush** [comment] 2018-03-01 16:56
Got same issue.
Revolved by granting full control access to `%userprofile%\vsdbg` and `%userprofile%\.nuget` for `Everyone` user

**Comment by ccit-spence** [comment] 2018-04-15 10:26
Same issues here, so far nothing as worked from above.  Reinstalled Docker, Reboots, New non AD user, Reset Permission, Add Share in Docker, New App API, New App MVC.  

Manually running docker-compose up works.  Nothing from VS2017 has worked.

**Comment by ccit-spence** [comment] 2018-04-15 21:58
@nicksterx I have a new machine. Base VS2017 Enterprise with no extensions. Used the standard web MVC template and the standard API template for core 2.0.

Now that being said, I got it working finally.

1. Created a local account.
2. Log in to new local account and access the files of the AzureAD user, press continue.
3. Restart
4. Now I can click the share in Docker preferences and it works.
6. May still see misc sharing problems, had to resolve one off.
5. MAYBE NEEDED?  Reinstalled VS 2017 - Reinstalled Docker
6. Ran this script `PS C:\> .\WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -Cleanup`  Located [here
](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking)
7. Deleted -> `%userprofile%\vsdbg` and `%userprofile%\clrdbg` 
8. Restarted and it now works.

I do believe I had two problems, not sure if related.  AzureAD accounts have issues.  Not sure if that created my other problems or I am lucky.

**Comment by mattwcole** [comment] 2018-04-15 22:39
I tend to run compose projects without the debugger attached (CTRL-F5) and there is no issue there. Any time I run with the debugger however I get the error above. This has been consistent on different machines, projects (including unaltered VS templates) and versions of VS and Docker for Windows for almost a year now.

**Comment by amang2205** [comment] 2018-04-19 11:31
I am impacted by this as well. Specifically, I can start the application without a debugger, but if I want to attach a debugger to the container, that fails.

**Comment by sd00887** [comment] 2018-04-26 01:03
会卡在%userprofiles%/vsdbg exists ,deleting，我的同事受到了此影响，对此的解决方案是重启Docker for windows 服务，然后再次运行调试，一切运行良好~~

**Comment by devarg** [comment] 2018-05-17 15:46
Same issue here but from visual studio appears this message

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
```

and then debugger does not attach nor keeps running

**Comment by joachimaumann** [comment] 2018-06-20 09:28
I have VS2017 14.7.4 and its not working for me. VS builds the container and its also running but I can not access it with the debugger. The message I get from the console is:

> Successfully built 163287ea0dc0
> Successfully tagged xxxxl:latest
> ========== Debugging ==========
> ========== Debugging ==========

**Comment by dbreshears** [comment] 2018-06-20 15:44
Tested 15.7.4 with  .NET Core 2.0 and Docker CE (Stable) Version 18.03.1-ce-win65 with Linux containers. and didn't see any issues.   Ensure that you are on that version of Docker.  Things to try:

Delete %userprofile%\vsdbg
Ensure Docker for Windows is in Linux mode
Reset credentials in Docker for Windows for the shared drives.  
Create a new .NET Core 2.0 MVC Web application and add Docker support with Linux
F5

If that doesn't work

-Reset Docker for Windows to Factory defaults or remove all containers and images
 via Powershell comand prompt
   docker rm -f (docker ps -a -q)
   docker rmi -f $(docker images -q)

If still not working, go to tools->options>Projects and Solutions->Build and Run and set "MSBuild project build output verbosity" to detailed and attach the logs from the "Build" and "Docker" output window panes

**Comment by aderderian** [comment] 2018-06-29 14:30
I have been impacted on this with Linux Containers as well. It definitely has something to do with Azure AD accounts. I tried to create a local account but due to my machine being joined to Azure AD I could not login to it and grant my new local user access to my %users% folder. I ended up having to create a local user with the same name as my Azure AD account and that "seemed" to work, but it is now failing.

**Comment by maroy1986** [comment] 2018-07-18 17:19
@dbreshears I have the exact same issue here, did you found a solution since your last post?

**Comment by dbreshears** [comment] 2018-07-27 22:19
No I have not?  What errors do you see? I assume you tried all the steps above with the latest 15.7 update of Visual Studio 2017 along with latest "Stable" channel of Docker For Windows.?      After F5, do you get a %userprofile%\vsdbg folder with the debugger there?    If a container is created , can you log into the container with "Docker exec -it <containerid> bash" and do you see a \remote_debugger folder with the debugger files in it?

**Comment by aderderian** [comment] 2018-07-27 22:29
Is there a way to do a screenshare for this? I would love to help you guys out, but pulling log files seems not productive.

Arra Derderian
President & CINO
www.cloudconstruct.com<http://www.cloudconstruct.com/>
arra@cloudconstruct.com<mailto:arra@cloudconstruct.com>
617-201-6138

[cid:D822F33A-2D8C-408A-B8B5-A51892BD3875]

**Comment by nicksterx** [comment] 2018-07-31 16:29
I think this issue might relate to how containers are built from docker-compose and including the vs debugger.

Jetbrains added support for debugging in docker with Rider and gives some insight about how it might work with Visual Studio. 

> Right now, only debugging ASP.NET Core web applications on Linux Docker containers is supported. And while Rider allows debugging containers that are built from a Dockerfile, it does not yet support debugging containers that are created using Docker compose (docker-compose.yml).

> Docker compose would require us to rewrite the docker-compose.yml to inject the debugger executable and configuration. It’s in our plans, but not there yet.



https://blog.jetbrains.com/dotnet/2018/07/18/debugging-asp-net-core-apps-local-docker-container/

**Comment by nicksterx** [comment] 2018-09-07 13:48
You could you post you docker-compose.yml?

**Comment by sega19** [comment] 2018-09-07 14:27
Sorry, I don't have the original yaml. I tweaked it buy putting some spaces before and after the colon, and the problem went away. None of the output windows showed a problem. Trying to do a project clean did show some sort of error. Never looked at the Errors list to see it something was being shown there.

**Comment by radhikaswift** [comment] 2018-09-07 15:54
Hi  Team ,I am new to docker.Configured docker for windows and developed docker file which builds nginx server to host angular application successfully.Now planning to call docker file in TFS build definition.I have added docker task to run command in Build deinftion but getting issue

018-09-07T15:44:05.6305242Z ##[debug]Absolute path for pathSegments: C:\Build\agent\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\NativeBinaries\amd64/docker = C:\_Build\agent\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\NativeBinaries\amd64\docker
2018-09-07T15:44:05.6305242Z ##[debug]Absolute path for pathSegments: C:\Program Files\Docker\Docker\/docker = C:\Program Files\Docker\Docker\docker
2018-09-07T15:44:05.6315253Z ##[debug]Absolute path for pathSegments: C:\Program Files\MongoDB\Server\4.0\bin/docker = C:\Program Files\MongoDB\Server\4.0\bin\docker
2018-09-07T15:44:05.6315253Z ##[debug]Absolute path for pathSegments: C:\Windows\system32/docker = C:\Windows\system32\docker
2018-09-07T15:44:05.6325187Z ##[debug]Absolute path for pathSegments: C:\Windows/docker = C:\Windows\docker
2018-09-07T15:44:05.6325187Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\Wbem/docker = C:\Windows\System32\Wbem\docker
2018-09-07T15:44:05.6335417Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\WindowsPowerShell\v1.0\/docker = C:\Windows\System32\WindowsPowerShell\v1.0\docker
2018-09-07T15:44:05.6345446Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft Network Monitor 3\/docker = C:\Program Files\Microsoft Network Monitor 3\docker
2018-09-07T15:44:05.6345446Z ##[debug]Absolute path for pathSegments: C:\Program Files\nodejs\/docker = C:\Program Files\nodejs\docker
2018-09-07T15:44:05.6355253Z ##[debug]Absolute path for pathSegments: C:\HashiCorp\Vagrant\bin/docker = C:\Vagrant\bin\docker
2018-09-07T15:44:05.6355253Z ##[debug]Absolute path for pathSegments: %USERPROFILE%\AppData\Roaming\npm/docker = C:\Build\agent\_work\1\s\%USERPROFILE%\AppData\Roaming\npm\docker
2018-09-07T15:44:05.6365241Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft\Web Platform Installer\/docker = C:\Program Files\Microsoft\Web Platform Installer\docker
2018-09-07T15:44:05.6365241Z ##[debug]Absolute path for pathSegments: C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps/docker = C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps\docker
2018-09-07T15:44:05.6375255Z ##[debug]check path : null
2018-09-07T15:44:05.6385223Z ##[debug]task result: Failed
2018-09-07T15:44:05.6465176Z ##[error]Unhandled: Failed which: Not found docker: null

1.

**Comment by ukian** [comment] 2018-09-14 06:10
the problem for  us was the short oneline error when we try and debug. Here's whats happening. if the app in %userprofile% are two directories. The short name shoulf have code in. If it is missing Or a day or two  stale it goes to   anothher url and usinng a magic url it retrieves thevsdbg files. the error refers to it not findikng the file as VSS version is in it.

We dont have a full solution we had to go home, we're closing in

**Comment by Neuroglia** [comment] 2018-09-22 00:49
I had the exact same problem. For me, removing the package 'Microsoft.VisualStudio.Web.CodeGeneration.Design' from my project solved it. I had an exception of the kind: Failed to find the assembly Microsoft.VisualStudio.Web.CodeGeneration.Design ... I missed it because, unlike most exceptions in the debug output, it basically is a one-liner. Hope this helps others in need!

**Comment by Neuroglia** [comment] 2018-09-22 00:50
The exception was:
Error:
  An assembly specified in the application dependencies manifest (ProductManager.deps.json) was not found:
    package: 'Microsoft.CodeAnalysis.CSharp.Workspaces', version: '2.8.0'
    path: 'lib/netstandard1.3/Microsoft.CodeAnalysis.CSharp.Workspaces.dll'

**Comment by tobecon** [comment] 2019-01-24 05:56
I am Chinese Developer . and I have this problem also .
eventually . I Found the possible reason .
1. the VS will First execute a ps1 script which located in  %userprofile%\AppData\Local\Temp\GetVsDbg.ps1
2. then I try to debug this ps1 Script File in vs code 
3. and I found the Script will download a zip file  which named https://vsdebugger.azureedge.net/vsdbg-16-0-11220-2/vsdbg-linux-x64.zip 
4. But in my china , because somereason It is so slow .
5 . I hope Microsoft  Solve this Issue make it download quickly

**Comment by 1015450578** [comment] 2019-01-24 05:59
https://developercommunity.visualstudio.com/content/problem/222255/docker%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E5%90%AF%E5%8A%A8%E8%B0%83%E8%AF%95.html

The solution may works for you

**Comment by TheRealVira** [comment] 2019-02-17 13:59
I have been getting the same debugging Error: "Cannot find container to attach, check if the correct container is running or not."

Have been following the steps of @joye-ramone [comment](https://github.com/Microsoft/DockerTools/issues/37#issuecomment-398798208) and get the following a very long output log (the las few lines):

```
1>Target "PostBuildEvent" skipped, due to false condition; ('$(PostBuildEvent)' != '' and ('$(RunPostBuildEvent)' != 'OnOutputUpdated' or '$(_AssemblyTimestampBeforeCompile)' != '$(_AssemblyTimestampAfterCompile)')) was evaluated as ('' != '' and ('' != 'OnOutputUpdated' or '' != '')).
1>Target "GenerateBuildDependencyFile" skipped. Previously built successfully.
1>Target "GenerateBuildRuntimeConfigurationFiles" skipped. Previously built successfully.
1>Target CoreBuild:
1>Target AfterBuild:
1>Target "ContainerPrepareForDotNetFrameworkBuild" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETFramework') was evaluated as ('.NETCoreApp' == '.NETFramework').
1>Target "ContainerPrepareForLaunch" skipped, due to false condition; (Exists('$(ContainerSemaphoreFilePath)')) was evaluated as (Exists('obj\Container\launch.sem')).
1>Target "DebugEnsureNodeEnv" skipped, due to false condition; ( '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ) was evaluated as ( 'Release' == 'Debug' And !Exists('ClientApp\node_modules') ).
1>Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
1>Target "_CheckForInvalidConfigurationAndPlatform" skipped. Previously built successfully.
1>Target ReportTypeScriptVersion:
1>  Task "FormatLocalizedString" skipped, due to false condition; ('$(TypeScriptVersionCheckResult)' == 'NoneSpecified') was evaluated as ('Good' == 'NoneSpecified').
1>  Task "FormatLocalizedString" skipped, due to false condition; ('$(TypeScriptVersionCheckResult)' == 'Downgrade' OR '$(TypeScriptVersionCheckResult)' == 'Upgrade') was evaluated as ('Good' == 'Downgrade' OR 'Good' == 'Upgrade').
1>  Task "Warning" skipped, due to false condition; ('$(TypeScriptShowVersionWarning)' == 'true' AND '$(TypeScriptVersionCheckResult)' == 'NoneSpecified') was evaluated as ('' == 'true' AND 'Good' == 'NoneSpecified').
1>  Task "Warning" skipped, due to false condition; ('$(TypeScriptShowVersionWarning)' == 'true' AND ('$(TypeScriptVersionCheckResult)' == 'Downgrade' OR '$(TypeScriptVersionCheckResult)' == 'Upgrade')) was evaluated as ('' == 'true' AND ('Good' == 'Downgrade' OR 'Good' == 'Upgrade')).
1>  Task "Warning" skipped, due to false condition; ('$(TypeScriptBuildMode)' == 'true' AND ($(TypeScriptToolsVersion.StartsWith('2.')) OR $(TypeScriptToolsVersion.StartsWith('1.')))) was evaluated as ('' == 'true' AND (False OR False)).
1>Target Build:
1>Target CleanupEmptyRefsFolder:
1>  Using "RemoveDir" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "RemoveDir"
1>    Directory "C:\Users\Administrator\Desktop\DA\Microservice\LoremIpsum\LoremIpsum\bin\Release\netcoreapp2.1\refs" doesn't exist. Skipping.
1>  Done executing task "RemoveDir".
1>Target "ExecuteToolsTarget" skipped, due to false condition; ('@(ToolsTarget)' != '') was evaluated as ('' != '').
1>Target "_PackAsBuildAfterTarget" skipped, due to false condition; ('$(GeneratePackageOnBuild)' == 'true' AND '$(IsInnerBuild)' != 'true') was evaluated as ('false' == 'true' AND '' != 'true').
1>Target "DotNetPublish" skipped, due to false condition; ( '$(DeployOnBuild)' == 'true' ) was evaluated as ( '' == 'true' ).
1>
1>Done building project "LoremIpsum.csproj".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.71
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by TheRealVira** [comment] 2019-02-17 14:01
Like, it does not even try to run it on docker..

**Comment by TheRealVira** [comment] 2019-02-17 14:18
However, starting `docker build - < Dockerfile` directly inside CMD does work...

**Comment by Rudithus** [comment] 2019-03-10 00:23
I've started encountering this problem after downgrading my compose file to 2.1

**Comment by vtcoder** [comment] 2019-04-28 00:09
In case this helps anyone else, I ran into the same thing: Debug run through vs.net 2017 15.9.8, failed with "You may only use the Microsoft .NET Core Debugger (vsdbg) with..." in the Debug output. Also attempting to build in Release config resulted in  error "Service 'abc' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder712245813/Docker: no such file or directory".

I tried all the suggestions above with no luck. For me it ended up being that the project name I used had spaces, e.g., "My Test Project". When I tried again with a fresh project with no spaces "MyTestProject", it worked.

For reference, this was a .net core console app, with docker support added via Add new item -> add docker ochestrator support. All defaults, no modification to docker file etc.

I can't say 100% that some of the above steps were not also required (since I performed them first), but I can say that I can still reproduce the issue with the project with spaces, and cannot with the project with no spaces. Hope this helps someone else b/c this was driving me crazy.

**Comment by bwateratmsft** [comment] 2019-05-01 13:28
@vtcoder The issue of spaces in the project name causing problems should be fixed in Visual Studio 2019. Can you try there?

**Comment by GreatFireWall** [comment] 2019-07-10 16:56
> I am a Chinese Developer . and I also have this problem .
> eventually . I Found the possible reason .
> 
> 1. the VS will First execute a ps1 script which located in  %userprofile%\AppData\Local\Temp\GetVsDbg.ps1
> 2. then I try to debug this ps1 Script File in vs code
> 3. and I found the Script will download a zip file  which named https://vsdebugger.azureedge.net/vsdbg-16-0-11220-2/vsdbg-linux-x64.zip
> 4. But in  china , because somereason It is so slow .
>    5 . I hope Microsoft  Solve this Issue make it download quickly

It sounds like that fuxking GFW cause this issue.

**Comment by janmchan** [comment] 2019-07-24 03:27
I have some easy repro steps:
- Create a dotnet core project
- Right click the project to add Docker Orchestration Support. This will create the docker compose project and docker file *inside* the project.
- Move the Dockerfile in the solution root and update the docker-compose.yaml to remove the project in the dockerfile path.
- From visual studio, click Docker Compose / F5 to debug
Expected : debugger starts and launches application
Actual: visual studio build using docker compose and finishes.

**Comment by bwateratmsft** [comment] 2019-07-24 13:36
@janmchan The Compose tools determine which projects to attach the debugger to based on which have a Dockerfile adjacent to the .csproj file. For example, you would not want to try to attach the debugger to a MySQL container, but you do want to attach to projects in your solution.

It is necessary to leave the Dockerfile adjacent to the project file if you want to attach to that project for debugging. It is still possible to launch it without attaching, though.

**Comment by chrislbb** [comment] 2019-11-18 09:58
I had the same issue but found this solution
for some reason VS 2019 could not download the linux debuger files from https://vsdebugger.azureedge.net/vsdbg-16-0-11220-2/vsdbg-linux-x64.zip.
The trick is to download this zip manually , unzipped the file and put all the files in %userprofile%\vsdbg\vs2017u5. I restarted docker and it worked for me.

**Comment by keltonjpsilva** [comment] 2020-05-03 16:09
> Got same issue.
> Revolved by granting full control access to `%userprofile%\vsdbg` and `%userprofile%\.nuget` for `Everyone` user

This work for me! Thanks! 
Can you help me with the Certificate?

**Comment by pratiksanglikar** [comment] 2020-09-28 20:17
I believe this issue is now resolved.
Please feel free to open a new issue if the problem still persists.

**Closed by pratiksanglikar** 2020-09-28 20:17 UTC

**Comment by alperenoz14** [comment] 2024-03-21 08:50
Got the same problem, Updated the docker desktop and that was the solution for me. fyi.
