### ISSUE TITLE
Impossible to Step Debug Docker Compose Project in VS 2019 with Regular DockerDevelopmentMode 

### ISSUE THREAD

**Issue by sikmowe** [microsoft/DockerTools#287] opened 2021-02-17 14:48 UTC
<H3> Background </H3>
The DockerDevelopmentMode was recently added as MicrosoftDocs/visualstudio-docs#4594 to overcome the fast mode when debugging is needed as https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#debugging
This issue dotnet/aspnetcore#18139 seemed to have solved in this version but lacks debug support when we run a docker compose project.

<H3>The bug</H3>
It is not possible to step debugging inside a container when the DockerDevelopmentMode was set to Regular in a docker compose project.  In fact, when we try to debug a docker compose project VS generate the following command in the build chain:

`docker-compose  -f "(...)docker-compose.yml" -f "(...)docker-compose.override.yml" -f "(...)\obj\Docker\docker-compose.vs.release.g.yml" (...)`

VS overrides a docker compose with the release yml. 

Maybe the solution could be change it to some debug.yml (with debug options enabled) with the regular behavior on (https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#debugging) to have all steps runned in the project Dockerfile.

<H3> To Reproduce </H3>

- Start Docker Desktop on Windows

- Create a new ASP.NET Core Web Application in Visual Studio
- Leave unchecked "Configure for HTTP" and "Enable Docker Support"
- Right click the project and choose "Docker Support..." and "Linux"
- Right click it again and choose "Container Orchestrator Support", "Docker Compose", "Linux" 
- Edit docker-compose.dcproj to add  
  `<DockerDevelopmentMode>Regular</DockerDevelopmentMode>`  
inside PropertyGroup tag and restart Visual Studio. 
- Toggle breakpoint in the start of "OnGet" method in Index.cshtml.cs file
- Right click docker-compose project and select "Set as Startup Project"
- Choose "Debug" Configuration
- Press F5 and check if the breakpoint is hitted

<H3>Technical details</H3>

- Output of ´dotnet --info´
```
.NET SDK:
 Version:   5.0.103
 Commit:    72dec52dbd

runtime:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- IDE
```
Microsoft Visual Studio Community 2019
Version 16.8.5
VisualStudio.16.Release/16.8.5+31005.135
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.559.8768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.559.8768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.559.8768
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.559.8768
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
```

**Comment by pratiksanglikar** [comment] 2021-02-17 18:15
Hi @sikmowe,
We have been able to reproduce the issue, and it is now under investigation.

**Comment by ucheNkadiCode** [comment] 2021-02-23 19:58
Hey @sikmowe, as our team investigates this issue, could you help us understand your scenario?

1. What are you trying to accomplish that requires you to debug outside of Fast Mode?
1. What is the reason you are in Debug mode and want to disable Fast Mode rather than switch your project to Release mode?
1. Does setting your project to Release mode solve your issue of disabling fast mode and successfully debugging your project?

Your answers to these questions would be highly appreciated!

**Comment by pratiksanglikar** [comment] 2021-02-23 20:29
Hi @sikmowe,
As I investigated the issue, I see that in the `Regular` mode, the project is always built in the `Release` configuration.
If you check the scaffolded `Dockerfile`, you can see in the `build` and `publish` stage, it uses `-c Release` flag that indicates it's a `Release` mode.

To enable debugging using `Debug` configuration and `Regular` mode, I would suggest using an arg for the configuration with a default value of `Release` and then overriding this arg in VS while debugging.
To achieve this do the following steps -

1. In the `build` stage in Dockerfile, add an arg for configuration as - `ARG Configuration=Release`.
2. In both the `build` and `publish` stage, replace `-c Release` with `-c ${Configuration}`.
3. Add a file `docker-compose.vs.release.yml` at the level where your `docker-compose.yml` file is located.
4. Override the Configuration arg in this newly added file by - 
```
version: '3.4'

services:
  <servicename>:
    build:
     args:
      - Configuration=Debug
```

This would allow you to debug your application using `Debug` configuration mode in `Regular` mode when you are using VS for debugging while not modifying the configuration for your CI/CD builds.

**Comment by sikmowe** [comment] 2021-02-25 11:01
Hi @ucheNkadiCode, thank you for your ready answer. Feel free to ask any other to clarify this request. Here you have my scenario in the answers of your question

1. I have some containers, the front end (SPA  with Angular) has several steps, so fast mode (that cuts some steps) does not fit well here.  Other containers with .NET Core would be fine to use this, since only the 'build' step creates what I need. The best configuration for productivity would be to have some (SPA) containers in regular mode and others in fast mode.

1. So the reason is the need of the front end to be completely assembled and to have a production-like environment to be debugged.

1. I'll try @pratiksanglikar tips and update this answer.

**Comment by pratiksanglikar** [comment] 2021-02-26 21:01
Hi @sikmowe,
Thank you for getting back to us with your use-case. I understand that you want to debug the frontend SPA and backend apps together, and that led you to choose the `Regular` mode for debugging.

I believe you can boost your productivity a little bit more by debugging in the `Fast` mode while your SPA app is built using all stages.
I see multiple options you could do that - 
1. Ignore the project in your docker-compose debugging setup with an attribute - `<DockerComposeProjectsToIgnore>`
    Add an attribute to your dcproj `<DockerComposeProjectsToIgnore>path\to\AngularProject1.csproj</DockerComposeProjectsToIgnore>`
This way your docker-compose setup won't try to execute in `Fast` mode for the Angular app but would do for other .NET Core apps.

2. Put the `Dockerfile` for the front-end project in a folder and update the references in the docker-compose file.
This would again achieve similar results as option 1.

I am glad the workaround I suggested earlier worked for you, I will close this issue for now.

**Closed by pratiksanglikar** 2021-02-26 21:01 UTC
Labels: under investigation

**Comment by eikesauer** [comment] 2022-03-18 10:58
> To enable debugging using `Debug` configuration and `Regular` mode, I would suggest using an arg for the configuration with a default value of `Release` and then overriding this arg in VS while debugging. To achieve this do the following steps -

If I'm not doing something wrong, this doesn't work in VS 2022. I see docker-compose.vs.release.yml used in a "config" step for Debug configuration in regular mode (which looks strange enough with the file being called release...), but not in the actual "build" step:

```
Build started...
[...]
2>docker-compose  -f "[...]\docker-compose.yml" -f "[...]\docker-compose.override.yml" -f "[...]\obj\Docker\docker-compose.vs.release.g.yml" -f "[...]\docker-compose.vs.release.yml" -p dockercompose15137891232477258720 --ansi never config
2>networks:
2>  pcpbackend:
2>    driver: bridge
2>    name: pcpbackend
2>services:
2>  webapi:
2>    build:
2>      args:
2>        Configuration: Debug
```

Yay!

```
2>WebApi -> [...]\WebApi\bin\Debug\net6.0\WebApi.dll
2>WebApi -> [...]\WebApi\obj\Debug\net6.0\PubTmp\Out\
2>docker-compose  -f "[...]\docker-compose.yml" -f "[...]\docker-compose.override.yml" -p dockercompose15137891232477258720 --ansi never build
2>Building webapi
2>#1 [internal] load build definition from Dockerfile
[...]
2>#11 20.69   Restored /src/PersistenceTests/PersistenceTests.csproj (in 19.27 sec).
2>#11 DONE 20.8s
2>#12 [build 5/8] RUN dotnet build "WebApi/WebApi.csproj" -c Release -o /app/build
```

Oopsies?

**Comment by ravipal** [comment] 2022-03-23 01:56
The regular mode built image is intended to be used outside of the machine where it is built. The docker-compose.vs.release.g.yml has some volume mounts to host machine that is used during local debugging. So, this file and docker-compose.vs.release.yml are not included during release mode build, otherwise this image will not work outside the host machine.

You could use `AdditionalComposeFilePaths` to pass additional overwrite file during compose build in regular mode. Here are the steps
1. In the docker-compose.dcproj define DockerDevelopmentMode as Regular
2. Add a conditional property AdditionalComposeFilePaths that points to the release mode overwrite file that defines the build argument
3. Rename your existing file docker-compose.vs.release.yml to docker-compose.release.yml (or whatever name you prefer and make sure to use the same file name in AdditionalComposeFilePaths.
4. The docker-compose project should look like this.
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" Sdk="Microsoft.Docker.Sdk">
  <PropertyGroup Label="Globals">
    ....
    <DockerDevelopmentMode>Regular</DockerDevelopmentMode>
  </PropertyGroup>
  <PropertyGroup Condition="$(DockerDevelopmentMode)==Regular">
    <AdditionalComposeFilePaths>docker-compose.release.yml</AdditionalComposeFilePaths>
  </PropertyGroup>
  <ItemGroup>
    <None Include="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.release.yml" />
    <None Include="docker-compose.yml" />
    <None Include=".dockerignore" />
  </ItemGroup>
</Project>
```
Now the docker-compose build should use the file docker-compose.release.yml.

You could also consider this https://github.com/microsoft/DockerTools/issues/287#issuecomment-786891693 suggestion.
