### ISSUE TITLE
Support for Docker 2.2.0

### ISSUE THREAD

**Issue by ffMathy** [microsoft/DockerTools#231] opened 2020-01-29 08:06 UTC
In Docker Desktop 2.2.0, shared drives are no longer needed.

The Container Tools should reflect this. It seems as if it is causing Visual Studio to detect that something is missing, because no shared drives are returned by Docker.

**Comment by pratiksanglikar** [comment] 2020-01-29 18:14
Hi @ffMathy please see [this comment](https://github.com/microsoft/DockerTools/issues/220#issuecomment-578908586)  on a similar bug.

**Comment by pratiksanglikar** [comment] 2020-01-29 18:17
Duplicate of #220

**Closed by pratiksanglikar** 2020-01-29 18:17 UTC
