### ISSUE TITLE
Error starting project with docker-compose

### ISSUE THREAD

**Issue by rgcooper2** [microsoft/DockerTools#157] opened 2018-11-07 10:33 UTC
After enabling container orchestrator support and selecting docker compose and linux as per https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker, I get the error below while building the project.

The project runs fine with IIS or as a single docker container but fails when running with docker compose.

```
1>docker-compose  -f "c:\temp\PsMovieStore\docker-compose.yml" -f "c:\temp\PsMovieStore\docker-compose.override.yml" -f "c:\temp\PsMovieStore\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose2591687191667203854 --no-ansi up -d --build --force-recreate --remove-orphans
1>[31940] Failed to execute script docker-compose
1>Traceback (most recent call last):
1>  File "docker-compose", line 6, in <module>
1>  File "compose\cli\main.py", line 71, in main
1>  File "compose\cli\main.py", line 124, in perform_command
1>  File "compose\cli\command.py", line 38, in project_from_options
1>  File "compose\cli\docker_client.py", line 84, in tls_config_from_options
1>  File "site-packages\docker\tls.py", line 81, in __init__
1>docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
```

**Comment by haniamr** [comment] 2018-11-30 22:00
Thanks @rgcooper2 for reporting this. This looks more like a docker-compose related issue.
One test you can try is to create a simple docker-compose file and dockerfile with the following contents:

docker-compose.yml

```
version: '3.4'

services:
  helloworldservice:
    image: helloworld:dev
    build:
      context: .
      target: base
      dockerfile: dockerfile
```
dockerfile
`FROM hello-world as base`

Then open a cmd in that directory and run: `docker-compose up`

Will that work?

**Comment by ramosisw** [comment] 2019-12-12 17:52
In my case I had an `.env` file with utf-16 encoding, I saved it as utf8 and it worked correctly.

**Comment by pratiksanglikar** [comment] 2020-09-28 18:49
@ramosisw I believe the issue is now resolved, so closing this issue.
Please feel free to open a new one if you are still having problems.

**Closed by pratiksanglikar** 2020-09-28 18:49 UTC
