### ISSUE TITLE
Consider copying NuGet.config to container if it exists when generating Dockerfile

### ISSUE THREAD

**Issue by oising** [microsoft/DockerTools#272] opened 2020-09-14 05:14 UTC
I used the "Add Docker support..." context menu item in VS 2019 to enable docker for a pre-existing ASP.NET core project. It generated a dockerfile, but unfortunately one of the dependencies was not in the standard nuget feed. I had added a second source (public source not private, so not related to authentication issues) to `NuGet.config` in the root of my solution and of course the docker build failed to restore because it did not copy this file before running restore. I added the following line to fix the problem. Consider automatically generating this line for a future release. Perhaps the ordering could be rearranged since there's also a `COPY . .` line which comes after the restore attempt?

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["NuGet.config", "."]
...
```
Thanks and keep up the good work.

**Comment by dbreshears** [comment] 2021-01-06 22:20
Looks like a duplicate of #117.  We can investigate adding that to the Dockerfile if we find a Nuget.config at the root.

**Comment by dbreshears** [comment] 2021-01-08 01:03
Closing this issue and will update #117 when we have a fix

**Closed by dbreshears** 2021-01-08 01:03 UTC
Labels: duplicate, enhancement
