### ISSUE TITLE
build hangs during docker-compose build image phase in Visual Studio 2017

### ISSUE THREAD

**Issue by kavhad** [Microsoft/DockerTools#150] opened 2018-09-19 08:11 UTC
Visual studio 2017 build hangs when building a solution with docker-compose project.

Microsoft Windows [Version 10.0.17134.285]
Docker version 18.06.1-ce, build e68fc7a

docker-compose.yml
```
version: '3.4'

services:
  myService:
    image: ${DOCKER_REGISTRY}x/test
    build:
      args:
        TARGET_SERVERCORE_VERSION: ${TARGET_SERVERCORE_VERSION}
      context: .\MyServiceProject
      dockerfile: Dockerfile
    environment:
    - "DbConnectionString=${DbConnectionString}"
    - "ELASTICSEARCH_URL=${ELASTICSEARCH_URL}"

```
.env file
```

DbConnectionString=xxxxxxxxx
TARGET_SERVERCORE_VERSION=1803
ELASTICSEARCH_URL=http://elasticsearch:9200
DOCKER_REGISTRY=

```

When build hangs, the following lines shows up in docker logs (C:\ProgramData\Docker\service.txt):

```
[09:41:57.805][WindowsDaemon  ][Info   ] debug: Calling POST /v1.30/build?t=+x%2test&q=False&nocache=False&rm=True&forcerm=False&pull=False&dockerfile=Dockerfile&buildargs=%7B%22TARGET_SERVERCORE_VERSION%22%3A+%221803%22%7D
[09:41:57.806][WindowsDaemon  ][Info   ] debug: FIXME: Got an API for which error does not match any expected type!!!: invalid reference format [module=api error_type=*errors.errorString]
```

If I remove the ${DOCKER_REGISTRY} parameter in the docker-compose.yml file build works again.

**Update**

To reproduce add DOCKER_REGISTRY as system environment variable in windows, with a single space char as value. Local .env file won't override windows global environment variable. Open a new command prompt and run docker-compose build as stated above.

**Comment by bwateratmsft** [comment] 2018-09-19 15:02
Hey @kavhad , I'm not able to reproduce your issue, but it looks similar to this issue:  moby/moby#35888. This user reported the same symptoms (timeout, then error), and has that same error message, "Got an API for which error does not match any expected type". Unfortunately, that issue is still open.

**Comment by kavhad** [comment] 2018-09-19 15:44
Ok, but one thing I noticed is that the docker service log is slightly different when I removed the DOCKER_REGISTRY parameter usage in docker-compose.yml,
a plus character didn’t appear in this location: ... /v1.30/build?t=+x%2test&q .
I wonder if this is causing issues and is due to windows end of line characters in .env file which is messing up the resulting call to build.

**Comment by bwateratmsft** [comment] 2018-09-19 15:53
@kavhad Great catch. That plus character there would be decoded as a space. Additionally, it may be a red herring, but where I would have expected a %2**F** (which is '/') between "x" and "test", instead it's just %2.
Try rearranging the .env file and trying different line ending formats. It's possible that it's misinterpreting a \r as a space and encoding a +, or something like that.

**Comment by kavhad** [comment] 2018-09-19 17:36
Sorry the **F** was there, bad cut&paste operation on my part :)

I realized my error, I had previously set the DOCKER_REGISTRY as environment variable in the windows system wide environment variables and It had been incorrectly set to a space character then. Oddly running docker-compose build didn't use the version of the variable set in the local .env file. Considering the .env file is local intuitively it should override the global system variable.

Sorry for the error on my part, but Docker tools for Visual Studio should be able to at least provide me a reason for failure and not just hang indefinitely without any messages. The error message given in the docker service logs is not very helpful either, but at least I was lucky enough to find a clue in there.

**Comment by bwateratmsft** [comment] 2018-09-19 17:44
No problem. I'll close this, glad I could sorta help!

**Closed by bwateratmsft** 2018-09-19 17:44 UTC
