### ISSUE TITLE
unknown flag: --target

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/DockerTools#80] opened 2018-03-02 14:41 UTC
_Copied from https://github.com/dotnet/dotnet-docker/issues/407 on behalf of @Yamdie_

## Steps to reproduce the issue
1. create project using VS 2017 
2. add docker
3. build

## Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		unknown flag: --target
See 'docker build --help'..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	366

**Comment by dbreshears** [comment] 2018-03-02 16:36
@Yamdie,  Can you share some more information 

- What Version of VS 2017 do you have
- What version of Docker For Windows do you have installed, is it in Linux or Windows mode?
-  What type of project are you creating,  .NET Core or .Net Framework, web or console?
-  Can you create the same project and not add docker support, does it run.  What if you add Docker support after validating it runs locally.   
- Can you share more of the build output?

**Comment by sriwantha** [comment] 2018-05-14 22:37
I get the same error. 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : unknown flag: --target

The problem is the docker build does not know the parameter called --target. 
For example, when I type 

docker build -help 

I don't see --target as an option/parameter. 


What Version of VS 2017 do you have: 
Visual studio community 15.6.7

What version of Docker For Windows do you have installed, is it in Linux or Windows mode?
Docker version 1.12.2-cs2-ws-beta, build 050b611

What type of project are you creating, .NET Core or .Net Framework, web or console?
.Net core web application . The error happens for .NET core console app also.

Can you create the same project and not add docker support, does it run. 
yes

What if you add Docker support after validating it runs locally.
Same error. The local docker engine does not have --target option 

Can you share more of the build output?

1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose10755373438112284764_webapplication2_" --format {{.ID}} -n 1
1>WebApplication2 -> C:\Temp\WebApplication2\WebApplication2\bin\Debug\netcoreapp2.0\WebApplication2.dll
1>docker build -f "C:\Temp\WebApplication2\WebApplication2\Dockerfile" --target "base" -t "webapplication2:dev" "C:\Temp\WebApplication2"
1>unknown flag: --target
1>See 'docker build --help'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : unknown flag: --target
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : See 'docker build --help'..
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by bwateratmsft** [comment] 2018-09-12 17:33
@sriwantha , is this actually [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/), not [Docker for Windows](https://store.docker.com/editions/community/docker-ce-desktop-windows)? Which version of Windows are you developing on? Please note that Docker Toolbox is not supported, only Docker for Windows.

**Comment by robertmuehsig** [comment] 2019-05-09 21:17
I have the same problem with VS 2019 and Docker for Windows.

Error message:
```
1>------ Build started: Project: Sloader.Fiddle, Configuration: Debug Any CPU ------
1>Sloader.Fiddle -> D:\Code\GitHub\Sloader\src\Sloader.Fiddle\bin\Debug\netcoreapp2.2\Sloader.Fiddle.dll
1>Sloader.Fiddle -> D:\Code\GitHub\Sloader\src\Sloader.Fiddle\bin\Debug\netcoreapp2.2\Sloader.Fiddle.Views.dll
1>docker build -f "D:\Code\GitHub\Sloader\src\Sloader.Fiddle\Dockerfile" -t sloaderfiddle:dev --target base  --label "com.microsoft.created-by=visual-studio" "D:\Code\GitHub\Sloader\src"
1>unknown flag: --target
1>See 'docker build --help'.
1>C:\Users\Robert\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.4.10\build\Container.targets(258,5): error CTP1001: An error occurred while attempting to build Docker image.
1>Done building project "Sloader.Fiddle.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
VS 2019 Info:

```
Microsoft Visual Studio Enterprise 2019 
Version 16.0.0
VisualStudio.16.Release/16.0.0+28729.10
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA866
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12311.10635
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.0.12311.10635
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12311.10635
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.7000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.0.12311.10635
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.7000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure HDInsight Azure Node   2.3.7000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.7000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.7000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61903.25110
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
```

Docker for Windows:
```
Version: 17.03.1-ce-rc1-win3 (10625)
Channel: edge
Sha1: 1795b358d57a91b5de5abac91fe6360420deb704
Started on: 2019/05/07 22:49:32.756
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\Robert\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
```

**Comment by sgreenmsft** [comment] 2019-05-09 21:22
@robertmuehsig - Could you share the content of the Build output window pane?  Additional details about this error can appear there.

**Comment by sgreenmsft** [comment] 2019-05-09 21:28
@robertmuehsig - Are you able to install a newer version of Docker Desktop?

https://docs.docker.com/docker-for-windows/release-notes/

**Comment by robertmuehsig** [comment] 2019-05-09 21:42
Ah - the update did the trick. Sorry - it seems I had a pretty old Docker installation, unfortunatly it branded itself as "edge channel", so I had the impression it is super new ;)

Works now 👍

**Comment by bwateratmsft** [comment] 2019-05-10 13:38
Glad to hear it's working! I'll close this issue now.

**Closed by bwateratmsft** 2019-05-10 13:38 UTC
