### ISSUE TITLE
Not able to build containers

### ISSUE THREAD

**Issue by machie27** [microsoft/DockerTools#224] opened 2019-12-18 12:31 UTC
I'm having a weird issue as my current tools won't build the containers. This is why i'm not able to debug. 
I get this generic error:
A non-critical error occurred while getting the container(s) ready. Your project(s) will continue to function normally. The error was: Object reference not set to an instance of an object.
If I hit f5 the following popup will emerge:
Unable to find the target operating system for the project.

The thing is if I create a new asp.net core project. It doesn't give me this error.
 There is something wrong in the warmup of the container and looks like it wont read one of the variable needed for the build command. However, with the current logging of the container tools I cannot find out where it went wrong.  Using Microsoft.VisualStudio.Azure.Containers.Tools.Targets
1.10.3 and VS 2019 16.5.0 Preview 1.0. 

For refernce my csproj file:
`
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>*****</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
`
And dockerfile:

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.10 AS base
WORKDIR /app

EXPOSE 5000
EXPOSE 44374

....

**Comment by machie27** [comment] 2019-12-18 15:42
For some further information See the obj\Container file with the one with the error:
![image](https://user-images.githubusercontent.com/6714617/71100468-607fb200-21b5-11ea-918e-764783ac59e8.png)
an the one which is working:
![image](https://user-images.githubusercontent.com/6714617/71100499-6ecdce00-21b5-11ea-8777-107af0512fdb.png)

**Comment by pratiksanglikar** [comment] 2019-12-18 21:44
hi @machie27 ,
1. Which version of `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` did you upgrade from?
2. Have you customized your `BaseIntermediateOutputPath` or `IntermediateOutputPath` using `Directory.Build.props`?
3. What's the behavior when you delete the `Obj` directory and then F5?

**Comment by machie27** [comment] 2019-12-19 08:03
Hi @pratiksanglikar ,

1. I came from 1.9.5
2. I haven't customized those paths
3. Still the same error, but no Container folder in object whatsoever.

Also diagnostic debugging doesn't give me any errors. It just skippes the ContainerBuildAndLaunch step.

**Comment by machie27** [comment] 2019-12-19 09:25
If I build with the build tools use, It does however build and runs. So it seems that one of those variables isn't set correctly. This is the command which I use:
`docker build -f "C:\Users\{username}\source\repos\{application}\{application}\Dockerfile" --force-rm -t {application}:dev --target base  --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name={application}" "C:\Users\{user}\source\repos\{application}" 
`

**Comment by machie27** [comment] 2019-12-19 13:27
Ok maybe not related, but I also made a new project and then changing the project name. Which will also causes the same error. Maybe it'll help with finding a solution

**Comment by machie27** [comment] 2020-01-23 13:44
I also have some build logs the correct one shows this

```
Done building target "AfterBuild" in project "WebApplication1.csproj". 1>Target "ContainerPrepareForDotNetFrameworkBuild" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETFramework') was evaluated as ('.NETCoreApp' == '.NETFramework'). 1>Target "ContainerBuildAndLaunch" in file "C:\Users***.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.10.6\build\Container.targets":

```
The wrong one show this:

```
>Done building target "AfterBuild" in project "{application}.csproj". 1>Target "ContainerLaunch" skipped, due to false condition; (Exists('$(ContainerSemaphoreFilePath)')) was evaluated as (Exists('obj\\Container\launch.sem')).
So it seems that the wrong build step is selected
```

**Comment by pratiksanglikar** [comment] 2020-01-23 20:01
Hi @machie27 ,
I tried to reproduce this issue with creating a project with Container.Tools version 1.9.5 and then upgrading to 1.10.3 but couldn't reproduce this issue.

Do you think you can provide a sample project where this issue is reproducing?
Or probably stripping your business logic in the project that has this issue and providing me that one?

**Comment by machie27** [comment] 2020-01-24 09:31
Ok I found something! Set this as a profile in launchsettings:
"Docker_Development": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/page",
      "environmentVariables": {
        "ASPNETCORE_URLS": "https://+:44374;http://+:5000",
        "ASPNETCORE_HTTPS_PORT": "44374",
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "publishAllPorts": true,
      "useSSL": true
    }
This will throw the errors above.

**Comment by machie27** [comment] 2020-01-24 09:40
With some further investigation changing the "docker" profile to anything other it will break the build of the container. We need different run profiles because of the environment settings. So I'll guess that's the exact bug.

**Comment by machie27** [comment] 2020-01-24 09:47
Ok further investigation revealed that changing the "docker" profile in launchSettings.json breaks the container warmup and also doesn't let the container build, with the error mentioned above.

So for example:
`
  "Docker Development": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/page",
      "environmentVariables": {
        "ASPNETCORE_URLS": "https://+:44374;http://+:5000",
        "ASPNETCORE_HTTPS_PORT": "44374",
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "publishAllPorts": true,
      "useSSL": true
    },
`
Will not work.

If we then change it back to: (It will run and build)
`
 "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/page",
      "environmentVariables": {
        "ASPNETCORE_URLS": "https://+:44374;http://+:5000",
        "ASPNETCORE_HTTPS_PORT": "44374",
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "publishAllPorts": true,
      "useSSL": true
    }
`
It will work

**Comment by pratiksanglikar** [comment] 2020-01-24 18:04
Thank you for finding the root cause. The fix for this issue is already in progress. We will update you when the fix becomes available in the Visual Studio.

**Comment by pratiksanglikar** [comment] 2020-01-24 18:07
Duplicate of #230

**Closed by pratiksanglikar** 2020-01-24 18:07 UTC
Labels: under investigation

**Comment by aligneddev** [comment] 2020-03-31 18:16
Is this fix in VS?

**Comment by pratiksanglikar** [comment] 2020-03-31 18:30
hi @aligneddev 
The actual fix for this issue is still internally implemented. We will let you know when the fix becomes available for download.

**Comment by maxpavlov** [comment] 2021-09-07 08:32
It's late 2021 and it is still relevant. Once VS goes into this state, the only thing that will enable anyone to rebuild and re-run the container for debugging would be to restart a VS instance. Other-wise Debug won't start and will throw the error in question.

**Comment by ravipal** [comment] 2021-09-07 23:58
@maxpavlov, As per the comment from #230 which is the duplicate of this is fixed and confirmed. If you are still having issue, please open a new issue with specific repro steps.
