### ISSUE TITLE
Adding Docker Support to Blazor Webassembly project breaks WebApplicationFactory

### ISSUE THREAD

**Issue by timmi-on-rails** [microsoft/DockerTools#262] opened 2020-07-06 22:17 UTC
1. Create a Blazor Webassembly Project template (version 3.2.0, Asp.net core hosted)
2. Create an Xunit test project.
3. Create a WebApplicationFactory<Startup> and use a generated client to fetch the root url "/" and ensure success (status code 200)
4. Execute the test and see it succeed.
5. Now add Docker Support (Linux) to the BlazorApp1.Server project.
6. The test will fail now. Root url responds with 404.

Removing the package reference solves the problem:
```<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />```
But then the docker support is gone.

Please confirm.
Here is the broken solution: https://github.com/timmi-on-rails/grpc/raw/master/docker-BlazorApp1.zip

**Comment by dbreshears** [comment] 2020-07-06 22:53
I'm able to reproduce, thanks for the repro project.   Investigating...

**Comment by timmi-on-rails** [comment] 2020-07-07 15:48
@dbreshears Thanks!

Maybe there is a correlation to this issue here: https://github.com/dotnet/aspnetcore/issues/21828?
I cannot verify, because I don't know these manifests they are talking about.

**Comment by dbreshears** [comment] 2020-07-07 16:24
@bwateratmsft , It turns out that with the Container tools targets enabled in the project,   the BlazorApp1.Server.StaticWebAssets.xml file never makes it to the XUnitTestProject1\bin\Debug\netcoreapp3.1 output folder.  That seems to be the delta between the working/non-working scenario.     If you manually copy that file into the folder, it seems to pass for me.  

 @timmi-on-rails,  We are investigating why this file is not making it there when are targets are included, but perhaps there is a workaround until this is resolved.

**Comment by NCarlsonMSFT** [comment] 2020-07-13 21:04
This does not appear to be an issue that is specific to the docker tools, this appears to be caused by exporting the IProjectGlobalPropertiesProvider. Here is a minimized repro project system that exports a single fake project property and causes the same behavior of the static assets file not being copied: [VSIXProject1.zip](https://github.com/microsoft/DockerTools/files/4915078/VSIXProject1.zip)

@dbreshears Do you know who would be a good person to talk to from the CPS or ASP.NET Core teams to investigate this further?

**Comment by javiercn** [comment] 2020-07-14 09:51
@dbreshears @NCarlsonMSFT I saw this issue and thought it might be related to https://github.com/dotnet/aspnetcore/issues/21828. [This](https://github.com/microsoft/DockerTools/issues/262#issuecomment-657793108) comment seems to point out that it might not be.

I can help if it is something on the SDK/MSBuild side, but I'm completely clueless WRT to CPS. Feel free to include me on any further discussion.

**Comment by dbreshears** [comment] 2024-08-01 19:26
Closing as 3.2 is out of support.

**Closed by dbreshears** 2024-08-01 19:26 UTC
