### ISSUE TITLE
Docker push to "Other Docker Container Registry" fails because of port in tag

### ISSUE THREAD

**Issue by LunicLynx** [microsoft/DockerTools#312] opened 2021-10-15 13:37 UTC
Hello,

in VS 2022 Preview 5. 

Currently if i push to `Other Docker Container Registry` the tooling appends the scheme port to the container image tag.

Which then fails on push:

![image](https://user-images.githubusercontent.com/9947716/137495880-faa135d5-4d6d-45e8-8885-399229c1f1bc.png)

I tried to locate the offending line of code in the nuget package, but wasn't able to find it.

Im using version 1.11.1 of the Nuget Package `microsoft.visualstudio.azure.containers.tools.targets`. 

Help would be greatly appreciated.

**Comment by evanmoak** [comment] 2022-10-05 21:19
Was this issue ever resolved? I am having the same issue pushing to GitHub Container Registry ghcr.io it appends ghcr.io:443 which gives a 404 not found error. 

We are not using Azure which is appears is the only available documentation on publishing to docker registries.

**Comment by LunicLynx** [comment] 2022-10-05 21:21
No it wasn't. I pushed the image manually via console after build.

**Comment by dbreshears** [comment] 2022-10-10 23:08
@evanmoak .    Thanks for bringing up.  This is now fixed internally and should release in a few weeks as part of 17.5 Preview 1

**Comment by dbreshears** [comment] 2022-10-17 19:20
@evanmoak.  Looks like we ran into a regression when testing this fix and need to reset my last comment.   Will let you know when have a resolution

**Comment by evanmoak** [comment] 2022-11-28 21:23
> @evanmoak. Looks like we ran into a regression when testing this fix and need to reset my last comment. Will let you know when have a resolution

Thanks for looking into it. Has there been any update into testing this solution?

**Comment by dbreshears** [comment] 2022-11-28 22:36
@evanmoak ,  thanks for the reminder.  We are continuing to look into this and should have more information soon.

**Comment by dbreshears** [comment] 2022-12-12 19:24
@evanmoak.  A fix for this is queued up again for 17.5 Preview 3.

**Comment by evanmoak** [comment] 2023-01-23 22:09
Hey Devin! I just noticed the launch of 17.5 Preview 3. I tried out the publish tools to "Other Container Registry" and used ghcr.io and the published worked as expected! VS tagged the image properly and completed the publish. 

Thank you so much for your work on this and constant updates!

**Closed** 2024-08-29 18:51 UTC
Labels: Fixed - Pending Release
