### ISSUE TITLE
LaunchSettings "publishAllPorts": true results in ERR_CONNECTION_REFUSED in browser

### ISSUE THREAD

**Issue by vikekh** [microsoft/DockerTools#326] opened 2022-02-01 16:29 UTC
I'm part of a team working on a shared codebase containing an ASP.NET Core 6 Web API targeting Docker on Linux.

We have the following default `launchSettings.json` for Docker target:

```{json}
"Docker": {
    "commandName": "Docker",
    "launchBrowser": true,
    "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
    "publishAllPorts": true,
    "useSSL": true,
    "sslPort": 5002
}
```

No matter what I try every time I run the project I get `ERR_CONNECTION_REFUSED`. If I change to `"publishAllPorts": false` it works and I can access Swagger UI locally at `https://localhost:5002/swagger`. I don't want to change the defaults if I'm the only one having problems and I cannot figure out why this change helps. I cannot see the setting listed [here](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2022) either.

Any idea on what to try?

- Windows 10
- Visual Studio Enterprise 2022 x64 v17.0.4
- Docker Desktop v4.4.4 (not WSL 2)
- `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` v1.14.0

**Comment by NCarlsonMSFT** [comment] 2022-02-04 01:44
@vikekh the impact of "publishAllPorts": true is that we will pass -P to docker run which will publish all exposed ports to a random port. However, when you specify a sslPort we do still pass -p 5002:443 so your service should still be listening on port 5002 (I just tested on my machine and got the expected behavior).
To help investigate this, when you change the value of publishAllPorts and F5 you can see the docker run command we use in the build output command window. The differences between the commands when publishAllPorts changes is presumabley the culprit.
You can also use the Containers tool window to inspect the mapped ports of the container to verify that port 443 has been mapped correctly.

**Comment by reecebradley** [comment] 2022-07-28 16:30
Almost same issue for me. I don't have specific ports setup
```json
"Docker": {
    "commandName": "Docker",
    "launchBrowser": true,
    "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
    "publishAllPorts": true
}
```

I can do docker run / compose for other containers, however, when I start debugging with VS 2022 I get  ERR_CONNECTION_REFUSED in the browser. I have tried a plethora of things. I use to think it was a me thing, then my coworker is having the same issue but one of my other coworkers doesn't.

After finding this, how can troubleshoot this the next level?

**Comment by NCarlsonMSFT** [comment] 2022-07-28 22:39
@reecebradley
* Is this HTTPS or HTTP? If HTTPS, can you check if the dev cert is trusted?
* If you open the containers window do you see [port mappings](https://docs.microsoft.com/en-us/visualstudio/containers/view-and-diagnose-containers?view=vs-2022#view-port-mappings)? If you click on those ports do you get a good response in the browser?
* Can you see connection attempts in the containers [logs](https://docs.microsoft.com/en-us/visualstudio/containers/view-and-diagnose-containers?view=vs-2022#view-logs)?

**Comment by reecebradley** [comment] 2022-07-29 13:41
The plot thickens, but first to answer your questions:
- Right now I am just trying to get HTTP working. 
- Yes, I see port mappings. When I click on the HTTP port binding, it opens a browser that lands then gives me `ERR_CONNECTION_REFUSED`
- I do not see any connection attempts in the logs.

## The VS 2022 Troubleshooting

Now for what I found out:
With VS 2022 open, successful build of project and app container running

(a)  I docker exec into my container and run **top**, this is the baseline, nothing running

![image](https://user-images.githubusercontent.com/1536861/181764973-098ae879-f2d8-4e93-9f5f-1d6cdba5c7f1.png)

(b) Start VS 2022 debug, opens browser to swagger endpoint, I end up here

**Browser**
![image](https://user-images.githubusercontent.com/1536861/181765189-543aa613-7cd2-4e1f-ad8f-c0b405610b5b.png)

**Container**
![image](https://user-images.githubusercontent.com/1536861/181765330-9da8f1ea-bd27-44d5-a9b1-de032aff3fd3.png)

**VS shows ports**
![image](https://user-images.githubusercontent.com/1536861/181766624-f3c0bae4-7696-442c-9fd5-4bc527a5ee51.png)


This is the problem just restated.

(c) Now I stop the debugger, goes back to 

![image](https://user-images.githubusercontent.com/1536861/181765593-f2af4c11-8aa4-4d69-bbff-4934290f2591.png)

(d) I open a 2nd shell into my container and run the app manually

![image](https://user-images.githubusercontent.com/1536861/181765916-7ffaa554-8b52-4df8-8724-d18448f1f4de.png)

(e) Now I end up when the same result

![image](https://user-images.githubusercontent.com/1536861/181767007-3cc6d21f-003d-4fa6-8de0-b91c8898566e.png)

Result was no change. 

## The Change and then It Works (Manual Creation)

(f) I then proceeded to create my own container using the same commands as VS 2022 but with a few parts changed

- Added `--rm`
- Changed `--name`
- Replaced `-P` with specific port binding `-p 8084:80`

This runs successful,.
just to show nothing is up my sleeves, I exec into the that container and run top:

![image](https://user-images.githubusercontent.com/1536861/181769827-96e13ace-33e2-40c4-8eb8-3fd0eb2a5d3d.png)

(g) Next I run the app manually via the shell, open a browser, **and it works!** ...*gasp*

![image](https://user-images.githubusercontent.com/1536861/181770332-88afe713-c365-4a82-8a6f-c1987822d9c6.png)

![image](https://user-images.githubusercontent.com/1536861/181770541-ece49ca6-698a-4384-af54-5efd8f6b53c1.png)

(h) I can even attach VS 2022 to the container process

![image](https://user-images.githubusercontent.com/1536861/181770850-c0d385b3-51d4-40d4-8920-f11266bd2ba6.png)

![image](https://user-images.githubusercontent.com/1536861/181770884-5859a546-8ba6-410a-9186-145adbc671d7.png)

![image](https://user-images.githubusercontent.com/1536861/181770902-6eed49bd-b93b-4d66-89ae-08befc468900.png)

## Thoughts

- So after my changes in (f), app works manually
- Could there be a bug with publishing all ports `-P` in docker?
- Is it port range?
- Is it the process initiating the docker commands, i.e. VS 2022?

**Comment by NCarlsonMSFT** [comment] 2022-07-29 23:11
@reecebradley A few potentially interesting things to try:
You can update your launch settings to use a fixed port:
```json
"Docker": {
  "commandName": "Docker",
  "launchBrowser": true,
  "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
  "publishAllPorts": false,
  "useSSL": false,
  "httpPort": 8084
}
```
If that unblocks debugging, then this would appear to be an issue with -P (this seems unlikely but worth checking)

Does debugging in the Release configuration work better? This uses less magic, and would point the finger of blame at the Debugging optimizations.

On a related note, does building the full image and running it work with -P?

If you use the fixed port, but don't change the name, does it still work?

**Comment by reecebradley** [comment] 2022-08-02 15:12
@NCarlsonMSFT 
😢

Rebooted my machine the issue is gone now. Another dev I work with had the same experience and he rebooted and it started working.

This has happened to me a number of times in the past so I guess I'll have to wait until it strikes again...

**Comment by reecebradley** [comment] 2022-08-04 19:52
@NCarlsonMSFT 
So it strikes again!

I started it up much like how my comments have been and it gave me that `ERR_CONNECTION_REFUSED`. I haven't rebooted sense, so its been like 2 days. I am running on a laptop for awareness.

## Trying Again
Any, I made this one change

```json
"Docker": {
  "commandName": "Docker",
  "launchBrowser": true,
  "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
  "useSSL": false,
  "httpPort": 8084
}
```

And it worked. So me being the curious sort, decided to try something else, I noticed with `publishAllPorts` enabled, the port was trying to use `49154` this time. So I decided to **kill** my container and start it back on that port `49154`, then I got build a error

```
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:49154 -> 0.0.0.0:0: listen tcp 0.0.0.0:49154: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
![image](https://user-images.githubusercontent.com/1536861/182934565-7f757cac-f94e-4730-b6f7-70560bc0f306.png)

Next I thought I would try another port, `49200` and got the same build error but on that port instead.

I proceeded to do sort of a discovery process to find the lowest and highest port, it seems `49152` - `49869` were giving me failures. Running `netstat -aon` just informed me of some ports being used by processes in that range but the ports I tried it didn't say anything was using that port. 

## More Thoughts

- I am guessing when `-P` is being used, and a port that was *thought* to be open but actually isn't, docker silently fails?
- I imagine there is a better explanation for what ` An attempt was made to access a socket in a way forbidden by its access permissions` means and perhaps a tool to identify ports that we shouldn't be using.

**Comment by NCarlsonMSFT** [comment] 2022-08-04 22:41
@reecebradley One of my teammates brought up the interesting question of are you using the WSL 2 backend? Their recollection is that the Hyper-V backend was more prone to port conflict errors.

**Comment by reecebradley** [comment] 2022-08-05 11:55
Rodger that, I am 

![image](https://user-images.githubusercontent.com/1536861/183072374-ad0b23e9-1b23-402b-b65d-33d8df7a4d46.png)

**Comment by NCarlsonMSFT** [comment] 2022-08-08 22:21
@reecebradley At this point I'd say this is an issue with Docker Desktop and there isn't much more I'm going to be able to offer to help. The only work-around I can recommend is updating your launch profiles to use a fixed port. Obviously, this isn't ideal, so hopefully you can reach out to Docker and they can provide better options.

**Comment by reecebradley** [comment] 2022-08-09 16:19
I found a similar sounding issue with docker cli and posted a summary of my findings and added a link back to this post.

https://github.com/docker/cli/issues/2980

**Comment by dbreshears** [comment] 2024-08-08 19:30
Closing as external

**Closed by dbreshears** 2024-08-08 19:30 UTC
Labels: External
